version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with dev --no-interaction

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
