# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - "pip install poetry"

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
